[package]
name = "cms-validate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boon = "0.5.1"
serde_json = "1.0.108"
